### PR TITLE
feat: add docker and nginx support

### PR DESCRIPTION
**Pull request by 97k**
[Short description explaining the high-level reason for the pull request]
api.localhost will direct to api on port 7242 and telemetry.localhost will open the Burr UI

## Changes
- add Docker support along with compose file
- nginx as a proxy for api and burr UI
- bug fixes

## How I tested this
Tested the docker build

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

----

> [!IMPORTANT]
> Adds Docker and Nginx support for email assistant with proxy configuration and minor server updates.
> 
>   - **Docker and Nginx Support**:
>     - Adds `Dockerfile` to set up a Python environment and run `wrapper.sh`.
>     - Adds `docker-compose.yaml` to define services for the app and Nginx, exposing ports 7241 and 7242.
>     - Adds `nginx.conf` to proxy `api.localhost` to port 7242 and `telemetry.localhost` to port 7241.
>   - **FastAPI Server**:
>     - Adds root endpoint in `server.py` to return a welcome message.
>     - Includes router with prefix `/email_assistant` in `server.py`.
>   - **Miscellaneous**:
>     - Fixes type hint bug in `_run_through()` in `server.py`.
>     - Adds `wrapper.sh` to start Burr UI and FastAPI server.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=DAGWorks-Inc%2Fburr&utm_source=github&utm_medium=referral)<sup> for 54a77358465740284c0c70a4148efb431218e47a. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by skrawcz — COMMENTED** [review]
Look great. Everything works. We just need to add to the README on how to run this (maybe even also put this as a comment in the docker file itself).

E.g. to run the UI, along with the email server backed, in a docker container:
1. `docker build . -t email_assistant`
2. `docker run  -it -p 7241:7241 -p 7242:7242  -e OPENAI_API_KEY='...' email-assistant`
3. Navigate to localhost:7242/docs for the email server running burr
4. Navigate to localhost:7241 for the Burr UI
5. Go to demos and play with the email-assistant if you don't have a UI. Else connect to the burr email server with your UI code.
Notes: this does not mount a persistent volume, so state is lost once the container goes down.


Any other caveats?

**Comment by 97k** [comment]
@skrawcz Yes, 
in fact
``` docker compose up --build``` is all that's required.

I will add a Readme file and yes there's no persistance.

**Comment by 97k** [comment]
@skrawcz Let me know if any changes are required.

**Review by skrawcz — APPROVED** [review]
:shipit:

**Pull request merged**
