### PR TITLE
Add collapse all feature

### PR DESCRIPTION
**Pull request by elijahbenizzy**
[Short description explaining the high-level reason for the pull request]

## Checklist

- [x] PR has an informative and human-readable title (this will be pulled into the release notes)
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code passed the pre-commit check & code is left cleaner/nicer than when first encountered.
- [ ] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future TODOs are captured in comments
- [ ] Project documentation has been updated if adding/changing functionality.

### CODE REVIEW

**Comment by skrawcz** [comment]
you need to rebase this branch?

**Comment by skrawcz** [comment]
seeing the JSON state is broken for me on this branch.

**Comment by elijahbenizzy** [comment]
> seeing the JSON state is broken for me on this branch.

Seems to work with mine. Rebased as well, perhaps that fixed it.

**Review by skrawcz — APPROVED** [review]
with the fixes this LGTM.

**Pull request merged**
