### PR TITLE
Adds JSON view for numeric list -- this is easier to deal with

### PR DESCRIPTION
**Pull request by elijahbenizzy**
We can just reuse the JSON view for this, its pretty clean.
image

### CODE REVIEW

**Comment by skrawcz** [comment]
will this work for top level number arrays too? I remember having code in two spots for this reason (IIRC).

**Comment by elijahbenizzy** [comment]
> will this work for top level number arrays too? I remember having code in two spots for this reason (IIRC).

From what I can tell that's actually not necessary. `FormRenderer` renders the data, but only the top level. That's always a `dict`/`object`, which means we just have to get the fields. The `RenderedField` is used recursively.

**Comment by skrawcz** [comment]
Cool -- but I see you've injected a `values` field in there though.

**Comment by skrawcz** [comment]
Screen Shot 2024-04-12 at 4 42 49 PM
fixed

**Comment by skrawcz** [comment]
note: rendering is a little sluggish with this.

**Review by skrawcz — APPROVED** [review]

**Pull request merged**
